sudo: false
language: python

matrix:
  include:
    - env: TOXENV=flake8
    - env: TOXENV=py3flake8
    - python: 2.7
      env: TOXENV=py27
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: pypy
      env: TOXENV=pypy
    # This should be tested. Problem is, Travis are using Python 3.2 for pypy3 which is no longer supported by pip
    # - python: pypy3
    #   env: TOXENV=pypy3

before_install:
  - pip install codecov
install:
  - pip install tox
script:
  - tox
after_success:
  - codecov
